#!/usr/bin/env python3
"""Post-scrape build step.

Reads site/data/rates.json and:
  1. writes site/data/rates.js  -> `window.__RATES__ = {...}`  (lets the
     dashboard work when opened as a local file:// without a server)
  2. appends today's snapshot to site/data/history.jsonl  (one line per day;
     re-running on the same day overwrites that day's line) so the dashboard
     can show day-over-day trend arrows.

Pure stdlib. Run after every rate update:  python3 scripts/build.py
"""
import json
import os
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "site", "data")
RATES_JSON = os.path.join(DATA, "rates.json")
RATES_JS = os.path.join(DATA, "rates.js")
HISTORY = os.path.join(DATA, "history.jsonl")


def main():
    with open(RATES_JSON, encoding="utf-8") as f:
        data = json.load(f)

    # 1. history snapshot (keyed by date; one entry per day)
    today = data.get("as_of", "")[:10] or date.today().isoformat()
    snapshot = {
        "date": today,
        "rates": {b["id"]: b["rates"] for b in data["banks"]},
    }

    lines = []
    if os.path.exists(HISTORY):
        with open(HISTORY, encoding="utf-8") as f:
            lines = [ln for ln in f.read().splitlines() if ln.strip()]
    # drop any existing entry for today, then append fresh
    lines = [ln for ln in lines if json.loads(ln).get("date") != today]
    lines.append(json.dumps(snapshot, ensure_ascii=False))
    with open(HISTORY, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # 2. shim for file:// usage (rates + recent history embedded)
    recent = [json.loads(ln) for ln in lines][-30:]
    with open(RATES_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build.py — do not edit by hand.\n")
        f.write("window.__RATES__ = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")
        f.write("window.__HISTORY__ = ")
        json.dump(recent, f, ensure_ascii=False)
        f.write(";\n")

    live = sum(1 for b in data["banks"] if b.get("status") == "live")
    print(f"build ok — {len(data['banks'])} banks ({live} live), history -> {today}")


if __name__ == "__main__":
    main()
